image: golang:latest
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
stages:
  - build
build:
  stage: build
  before_script:
    - apt-get update -q > /dev/null 2>&1 || echo " ! failed to update package lists"
    - apt-get install -q -y make cmake openssl-dev libssh2 libgit2
  script:
    - make dependencies
    - make build
  cache:
    paths:
      - sources/
  artifacts:
    paths:
      - go-build
    expire_in: 1hr
