image: golang:alpine
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
stages:
  - build
build:
  stage: build
  before_script:
    - apk update
    - apk add bash git go upx make cmake openssl-dev libssh2 libgit2
  script:
    - make dependencies
    - make build
  cache:
    paths:
      - sources/
  artifacts:
    paths:
      - go-build
    expire_in: 1hr
