image: golang:alpine
cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
stages:
  - build
build:
  stage: build
  before_script:
    - apk update
    - apk add --no-cache gcc musl-dev libc-dev g++ alpine-sdk bash git go upx make cmake python3 openssl-dev curl libcurl curl-dev libgcrypt libgcrypt-dev libssh libssh-dev libssh2 libssh2-dev
#    - apk add libgit2 libgit2-dev
  script:
    - . ./build-dependencies.sh && make build
  cache:
    paths:
      - sources/
  artifacts:
    paths:
      - go-build
    expire_in: 1hr
